### ISSUE TITLE
The directory existing is not enough of a check that a package has been built

### ISSUE THREAD

**Issue by RlndVt** [vale981/archiso-bcachefs#1]
A better check is needed for whether or not a package exists and is valid. My interim suggestion:

    if [ ! -d "$NAME" ]; then
        git clone $URL
        cd $NAME
    else
        cd $NAME
        git pull
    fi

    makepkg -s

**Comment by vale981** [comment]
78d553eeec20ff9ee6fe4a2474b0a2245ab60981
